# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhotel.proto\x12\x05hotel\"c\n\x0cHotelRequest\x12\r\n\x05stars\x18\x01 \x01(\x05\x12\x15\n\rall_inclusive\x18\x02 \x01(\x08\x12\x14\n\x0croom_service\x18\x03 \x01(\x08\x12\x17\n\x0f\x61irport_shuttle\x18\x04 \x01(\x08\"#\n\rHotelResponse\x12\x12\n\nhotel_data\x18\x01 \x01(\t2@\n\x05Hotel\x12\x37\n\x08GetHotel\x12\x13.hotel.HotelRequest\x1a\x14.hotel.HotelResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hotel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HOTELREQUEST']._serialized_start=22
  _globals['_HOTELREQUEST']._serialized_end=121
  _globals['_HOTELRESPONSE']._serialized_start=123
  _globals['_HOTELRESPONSE']._serialized_end=158
  _globals['_HOTEL']._serialized_start=160
  _globals['_HOTEL']._serialized_end=224
# @@protoc_insertion_point(module_scope)
