# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.flight_pb2 as flight__pb2


class FlightStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFlight = channel.unary_unary(
                '/flight.Flight/GetFlight',
                request_serializer=flight__pb2.FlightRequest.SerializeToString,
                response_deserializer=flight__pb2.FlightResponse.FromString,
                )


class FlightServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFlight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlight,
                    request_deserializer=flight__pb2.FlightRequest.FromString,
                    response_serializer=flight__pb2.FlightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flight.Flight', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Flight(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.Flight/GetFlight',
            flight__pb2.FlightRequest.SerializeToString,
            flight__pb2.FlightResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
