# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.pb.hotel_pb2 as hotel__pb2


class HotelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHotel = channel.unary_unary(
                '/hotel.Hotel/GetHotel',
                request_serializer=hotel__pb2.HotelRequest.SerializeToString,
                response_deserializer=hotel__pb2.HotelResponse.FromString,
                )


class HotelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHotel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHotel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHotel,
                    request_deserializer=hotel__pb2.HotelRequest.FromString,
                    response_serializer=hotel__pb2.HotelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel.Hotel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Hotel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHotel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel.Hotel/GetHotel',
            hotel__pb2.HotelRequest.SerializeToString,
            hotel__pb2.HotelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
